### ISSUE TITLE
[FEAT ✨] Support landscape mode

### ISSUE THREAD

**Issue by gwendall** [luicfrr/react-native-vision-camera-face-detector#62]
When switching to landscape mode the detections appear erratic. Is there something we can do to support them better in the current version?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/luicfrr) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/luicfrr/react-native-vision-camera-face-detector/issues/62">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/luicfrr/react-native-vision-camera-face-detector/issues/62/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/luicfrr/react-native-vision-camera-face-detector/issues/62/pledge.svg">
</picture>
</a>

**Comment by luicfrr** [comment]
can you add a screenshot or a video showing what you mean with "detections appear erratic"?

**Comment by luicfrr** [comment]
Okay, can you please check if `frame.orientation` change when you rotate your device?

Currently I’m using frame’s orientation to determine MLKit orientation.

**Comment by gwendall** [comment]
Oddly `frame.orientation` never changes. Orientation change does get captured with [`expo-screen-orientation`](https://docs.expo.dev/versions/latest/sdk/screen-orientation/) though.
https://github.com/luicfrr/react-native-vision-camera-face-detector/assets/329887/729e4ba3-4328-4c12-918a-e8615c76f3f6

**Comment by mrousavy** [comment]
Okay I definitely need to update the documentation on `frame.orientation` as a lot of people seem to misunderstand what it actually means and I get asked about this almost daily.

1. Orientation is not fully implemented. I'm trying to raise money so I can implement orientation here: https://github.com/mrousavy/react-native-vision-camera/issues/1891 
2. The orientation of the `Frame` is probably not what most people think under orientation. Maybe I can find a different name for it. But it is always the way you need to read the Frame to make sure it is up-right. That's because Camera sensors are often in landscape orientation and that means you need to rotate the Frame by 90deg to display it up-right. This is handled already for preview photo and video, but in Frame Processors you need to do it yourself - if I would always rotate the frame to be 90deg upright position, that would introduce a huge latency and performance bottleneck in the pipeline. So instead, ML models work by internally just reading the Frame rotated. That way I don't have to actually rotate any buffers around and it's much faster. 

Hope this explains why it stays the same.

**Comment by luicfrr** [comment]
I'll do some tests and try to implement this feature ASAP. The problem is I'm busy with another project right now so I can't say when I'll have time to do this.

Anyway, if you want to try it yourself: orientation is handled on native side in these lines:

https://github.com/luicfrr/react-native-vision-camera-face-detector/blob/4d3629e426feadbdb9e223b025b9cfd7acc60af6/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPlugin.kt#L251-L262

https://github.com/luicfrr/react-native-vision-camera-face-detector/blob/4d3629e426feadbdb9e223b025b9cfd7acc60af6/ios/VisionCameraFaceDetector.swift#L220-L231

a good start point is to set fixed values on native side and check if it works:
```
// ios
let image = VisionImage(buffer: frame.buffer)
image.orientation = .up //or .left or .right etc....

// android
val image = InputImage.fromMediaImage(frame.image, 0) // or 90, 180, etc...
```

maybe we can add the `orientation` prop on config so when orientation changes it will recreate face detector:
```
const orientation = someOrientationHook() 
const { detectFaces } = useFaceDetector( {
  ... other props,
  orientation
} )
```

Or maybe get device's orientation on native side instead?

**Comment by luicfrr** [comment]
@gwendall I just released `1.7.0` version. 
Can you please check if it really fix this issue?

**Comment by dkoh555** [comment]
> @gwendall I just released `1.7.0` version. Can you please check if it really fix this issue?

I think the issue still isn't fixed. When I run the face detector in a landscape orientation the detections are erratic, similar to what was described by the OG post.

In @mrousavy's post about frame.orientation (https://github.com/mrousavy/react-native-vision-camera/pull/3077), he mentions that the frame is "... always some fixed orientation (e.g. landscape-left), no matter if the phone is in portrait or landscape".

He then mentions that Frame Processor Plugin authors need to adjust their respective Plugins accordingly so that the Plugins themselves compensate for any rotations that the user may encounter or use.
He states that "If the user holds his phone sideways (aka not in it's native portrait orientation), then you would also need to rotate that Orientation".

This is an option I don't believe is currently available in this pacakge, and would really appreciate it if it got added!
That said, there could be something obvious that I'm missing so please advise in the case that I am!

**Comment by luicfrr** [comment]
@dkoh555 The issue is reopened but I don't have time to work on this package right now.
Anyway you're wellcome to open a PR anytime.

**Comment by luicfrr** [comment]
I added some commits that now seems to fix orientation issue.
Can you guys test it before I release it as a new version?

**Comment by luicfrr** [comment]
fixed in c1cce1b
