### ISSUE TITLE
[BUG 🐛] CocoaPods could not find compatible versions for pod "VisionCameraFaceDetector".... but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by manivelgopi** [luicfrr/react-native-vision-camera-face-detector#64]
React-native cli
<img width="950" alt="Screenshot 2024-05-22 at 22 09 16" src="https://github.com/luicfrr/react-native-vision-camera-face-detector/assets/52520718/8792fffd-0ee3-40c4-8063-85c7b9e452b4">

[!] CocoaPods could not find compatible versions for pod "VisionCameraFaceDetector":
  In Podfile:
    VisionCameraFaceDetector (from `../node_modules/react-native-vision-camera-face-detector`)

Specs satisfying the `VisionCameraFaceDetector (from `../node_modules/react-native-vision-camera-face-detector`)` dependency were found, but they required a higher minimum deployment target.

[!] [Codegen] warn: using experimental new codegen integration
error Command failed with exit code 1.

**Bug:**
Facing Target version compatibility issue while installing pod.  -> `cd ios && bundle install && bundle exec pod install `

**I have tryed:**
I have tryed replacing this s.platforms    = { :ios => "14" }  with   s.platforms    = { :ios => "13.8" } in VisionCameraFaceDetector.podspec  But still `yarn start` getting failed due to incompatible pod package issues.. 

**`my package.json` file:**
React-native cli
{
   "dependencies": {
     "react-native-vision-camera": "4.0.4",
     "react-native-vision-camera-face-detector": "1.6.3",
     "react-native-worklets-core": "1.3.3"
  }
}

**Comment by luicfrr** [comment]
> Specs satisfying the VisionCameraFaceDetector (from ../node_modules/react-native-vision-camera-face-detector) dependency were found, but they required a higher minimum deployment target.

That's the answer

> I have tryed replacing this s.platforms = { :ios => "14" } with s.platforms = { :ios => "13.8" } in VisionCameraFaceDetector.podspec But still yarn start getting failed due to incompatible pod package issues..

I can't guarantee the package will work on non-tested version so I'm closing the issue.

**Comment by frodriguez-hu** [comment]
I am having the issue on an empty new React Native Project

```
[!] CocoaPods could not find compatible versions for pod "VisionCameraFaceDetector":
  In Podfile:
    VisionCameraFaceDetector (from `../node_modules/react-native-vision-camera-face-detector`)

Specs satisfying the `VisionCameraFaceDetector (from `../node_modules/react-native-vision-camera-face-detector`)` dependency were found, but they required a higher minimum deployment target.
```

My deployment target is 14.0 which is the minimum of the library, that message should not appear. @luicfrr Why can't we reopen this issue?

**Comment by frodriguez-hu** [comment]
Well... it worked hardcoding this: `platform :ios, min_ios_version_supported`
by `platform :ios, "14.0"` on the Podfile, but I don't know where the `min_ios_version_supported` is being get

**Comment by luicfrr** [comment]
> Well... it worked hardcoding this: `platform :ios, min_ios_version_supported` by `platform :ios, "14.0"` on the Podfile, but I don't know where the `min_ios_version_supported` is being get

this is the right way

**Comment by serranoarevalo** [comment]
If anyone is facing this while using Expo's EAS build here is how I fixed it using [Expo BuildProperties](https://docs.expo.dev/versions/latest/sdk/build-properties/)

1- Run `npx expo install expo-build-properties`
2- In `app.json` add under `"plugins"`:

```json
[
  "expo-build-properties",
  {
    "ios": {
      "deploymentTarget": "14.0"
    }
  }
]
```

**Comment by Avinash-icode49** [comment]
Even after changing platform :ios to "14.0", the issue is still not resolved.
